#!/usr/bin/env node
/**
 * scaffold_validation_test.js — generates the files needed to validate a
 * project's schema.org structured data from its OWN test suite, so the markup
 * this skill adds keeps getting re-checked on every future build.
 *
 * Two project shapes are supported (see references/regression-tests.md):
 *   --type eleventy   validate 11ty's built HTML output (post-build).
 *   --type component  validate design-system components' rendered output.
 *
 * Like the injector/generator, this NEVER writes files. It prints the three
 * files (a vendored validation core, a throwing assert helper, and a
 * runner-appropriate test) to stdout with `=== file: <path> ===` headers for
 * review; add them to the project once you've looked them over.
 *
 * Usage:
 *     node scaffold_validation_test.js --type eleventy  --runner node   [--out tests] [--site-dir _site]
 *     node scaffold_validation_test.js --type component --runner vitest [--out tests] [--render-module ../src/render.js]
 *
 * Requires (to run this generator): nothing beyond Node. The generated tests
 * require the consumer to have `cheerio` and `jsonld` as devDependencies.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { parseArgs } from "./inject_microdata.js";

const HERE = path.dirname(fileURLToPath(import.meta.url));

// The `test` import differs per runner; everything else in the generated test
// is identical because the assert helper throws (a thrown error fails a test
// in every one of these runners).
const RUNNER_IMPORTS = {
	node: 'import { test } from "node:test";',
	vitest: 'import { test } from "vitest";',
	jest: 'import { test } from "@jest/globals";',
};

export function runnerImport(runner) {
	const line = RUNNER_IMPORTS[runner];
	if (!line) {
		throw new Error(`unknown --runner '${runner}' (expected: ${Object.keys(RUNNER_IMPORTS).join(", ")})`);
	}
	return line;
}

const GENERATED_BANNER =
	"// Generated by the structured-data skill (scaffold_validation_test.js).\n" +
	"// Requires devDependencies: cheerio, jsonld.";

export function buildEleventyTest({ runner, siteDir = "_site" } = {}) {
	return `${GENERATED_BANNER}
// Validates the schema.org structured data in 11ty's BUILT output. Run this
// AFTER \`eleventy\` has produced the site -- it reads the built HTML, not the
// templates. Wire it into CI as: build, then test.
${runnerImport(runner)}
import { readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";
import { assertStructuredDataValid } from "./structured-data-assert.js";

const SITE_DIR = ${JSON.stringify(siteDir)};

function htmlFiles(dir) {
	const out = [];
	for (const entry of readdirSync(dir)) {
		const p = join(dir, entry);
		if (statSync(p).isDirectory()) out.push(...htmlFiles(p));
		else if (p.endsWith(".html")) out.push(p);
	}
	return out;
}

test("built site has valid schema.org structured data", async () => {
	const files = htmlFiles(SITE_DIR);
	if (files.length === 0) {
		throw new Error(\`no built HTML found under \${SITE_DIR} -- run the 11ty build first\`);
	}
	for (const file of files) {
		await assertStructuredDataValid(readFileSync(file, "utf8"), { label: file });
	}
});
`;
}

export function buildComponentTest({ runner, renderModule = "../src/render.js" } = {}) {
	return `${GENERATED_BANNER}
// Validates the structured data your design-system components emit. Each case
// renders a component to an HTML STRING (the markup a crawler receives) and
// asserts it's valid. Client-only rendering can't be validated here -- and
// wouldn't be crawlable anyway; render server-side / to static markup.
${runnerImport(runner)}
import { assertStructuredDataValid } from "./structured-data-assert.js";

// TODO: point this at your component render entry. It must return HTML as a
// string -- e.g. React's renderToStaticMarkup, Vue's renderToString, or your
// Web Component's Declarative Shadow DOM SSR output.
import { renderComponent } from ${JSON.stringify(renderModule)};

// One entry per component (or variant) that carries structured data.
const CASES = [
	// {
	// 	name: "ProductCard",
	// 	render: () => renderComponent("ProductCard", { price: "49.99", currency: "USD" }),
	// },
];

for (const c of CASES) {
	test(\`\${c.name} emits valid structured data\`, async () => {
		await assertStructuredDataValid(await c.render(), { label: c.name });
	});
}

// Fails until you configure CASES above — a validation test that validates
// nothing should not report green. Delete this once CASES is populated.
test("structured-data component cases are configured", () => {
	if (CASES.length === 0) {
		throw new Error(
			"No component CASES configured — add your structured-data components above so this suite actually validates something (delete this guard once done)."
		);
	}
});
`;
}

export function buildTest(type, opts) {
	if (type === "eleventy") return buildEleventyTest(opts);
	if (type === "component") return buildComponentTest(opts);
	throw new Error(`unknown --type '${type}' (expected: eleventy, component)`);
}

/**
 * Read the two files that get vendored verbatim into the consumer project.
 * Returns [{ name, contents }] in dependency order (core before assert).
 */
export function readVendorFiles() {
	return [
		{ name: "structured-data-core.js", contents: fs.readFileSync(path.join(HERE, "structured-data-core.js"), "utf8") },
		{ name: "structured-data-assert.js", contents: fs.readFileSync(path.join(HERE, "structured-data-assert.js"), "utf8") },
	];
}

const USAGE =
	"Usage: node scaffold_validation_test.js --type <eleventy|component> [--runner node|vitest|jest] [--out tests]";

export function main(argv = process.argv.slice(2)) {
	if (argv.includes("--help") || argv.includes("-h")) {
		console.log(USAGE);
		return;
	}
	const args = parseArgs(argv);
	const type = args.type;
	const runner = args.runner || "node";
	const outDir = args.out || "tests";

	if (!type) {
		console.error(USAGE);
		process.exit(1);
	}

	let testContents;
	try {
		testContents = buildTest(type, {
			runner,
			siteDir: args["site-dir"],
			renderModule: args["render-module"],
		});
	} catch (err) {
		console.error(`error: ${err.message}`);
		process.exit(1);
	}

	const testName = `structured-data.${type}.test.js`;
	const files = [...readVendorFiles(), { name: testName, contents: testContents }];

	console.error(
		`# Review these ${files.length} files, then add them under ${outDir}/. ` +
			`The consumer needs cheerio + jsonld as devDependencies.\n`
	);
	for (const f of files) {
		process.stdout.write(`=== file: ${path.join(outDir, f.name)} ===\n`);
		process.stdout.write(f.contents);
		if (!f.contents.endsWith("\n")) process.stdout.write("\n");
		process.stdout.write("\n");
	}
}

if (import.meta.url === pathToFileURL(process.argv[1] || "").href) {
	main();
}
